### ISSUE TITLE
Homebridge accessories unresponsive/slow when plugin is installed

### ISSUE THREAD

**Issue by marcandre83** [russtone/homebridge-mi-humidifier#27] opened 2020-04-21 14:39 UTC
Hi,

I am using homebridge with this plugin in two different homes, each equipped with the cb1 humidifier. I open the Apple Home.app and after some time showing "updating", all Homebridge accessories show "No Response". I then have to close and re-ope the Home.app and the Homebridge accessories work. On both homes this only happens when the mi-humidifier plugin is installed. Do you have any idea what can be causing this?

Thank you very much

**Comment by earlywaff** [comment] 2020-04-21 15:13
I agree! Same problem. I had to demolish this plugin so far.
You have to go into the home kit twice to get the correct status in the home kit.

------
Согласен! Такая же проблема. Пришлось пока снести этот плагин. 
Приходиться два раза перезаходить в ХК для того, чтобы получить корректный статус.
Но у меня новый увлажнитель, который добавили пару часов назад.
Возможно ли решение данной проблемы?(

**Comment by Aekung** [comment] 2020-04-27 02:15
Hi,

Having the same problem as well. Homebridge accessories become unresponsive for the first trial. Need to reload Home App (by both quitting the app or swipe to another room then swipe back) in order to have all accessories become responsive once again.

Home it will be fixed since I love controlling my humidifier in HomeKit.

Thank you.

**Comment by bedrin** [comment] 2020-04-27 07:51
Duplicate of https://github.com/russtone/homebridge-mi-humidifier/issues/21

**Closed** 2020-04-28 18:11 UTC
Labels: duplicate
