### ISSUE TITLE
Xiaomi deerma support request (python-miio already support this model)

### ISSUE THREAD

**Issue by RAZRu** [russtone/homebridge-mi-humidifier#19] opened 2019-12-07 23:18 UTC
Hi!
Could you please add support to xiaomi deerma Humidifier https://www.xiaomiyoupin.com/detail?gid=109486 when you have free time? 

python-miio already supports this model 
https://github.com/rytilahti/python-miio/issues/533

**Comment by RAZRu** [comment] 2019-12-07 23:56
nah, it's another library
Can you switch to not dead library?

**Comment by haiyeung** [comment] 2019-12-19 04:23
support! i buy this humidifer recently

**Comment by Aekung** [comment] 2020-01-26 16:39
Hope to see update on this as well since this model "mjjsq" is already supported by python-miio.

Looking forward to the update if possible.

Thank you.

**Comment by earlywaff** [comment] 2020-02-03 09:30
Looking forward to the update if possible!
TNX!)

**Comment by PietroLubini** [comment] 2020-04-18 21:40
I've added support for "deerma.humidifier.mjjsq". @russtone, create a branch for me to push the changes, please.

**Comment by Donni1966** [comment] 2020-04-19 11:07
Hey that cool, @PietroLubini. 
i've get the new Humidifier yesterday. Wait for support to integrate this in my hombrigde installation.

**Comment by russtone** [comment] 2020-04-19 11:10
Hi @PietroLubini, you can create a pull request and I will merge it

**Comment by Aekung** [comment] 2020-04-21 08:39
Hi,

May I know how to update the plugin to support deerma as done by @Donni1966 ?

Thank you and looking forward to hearing from you.

**Comment by russtone** [comment] 2020-04-21 08:53
Hi, I've just merged @PietroLubini pull request and released new version

**Comment by Aekung** [comment] 2020-04-21 08:55
> Hi, I've just merged @PietroLubini pull request and released new version

Thanks. I'm updating the plugin =)

**Comment by Donni1966** [comment] 2020-04-21 09:39
Hi. 
1. very thanx to support the ne model. 

i updated and i get humintity an Temp and an control, but in the log of the HB is see this

    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8) {
  code: -30012
}
[4/21/2020, 11:25:34] [Luftbefeuchter Offie] getWaterLevel Error: busy.
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8) {
  code: -30012
}
[4/21/2020, 11:25:34] [Luftbefeuchter Offie] getRotationSpeed Error: busy.
    at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
    at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8) {
  code: -30012
}

any idear?

**Comment by russtone** [comment] 2020-04-21 09:48
This looks like #21, I've tried to fix this error, but I can't reproduce it with my v1 model. It will be helpful if you can collect some debug logs by running homebridge like this:

```
DEBUG=miio*,thing* homebridge -D
```

**Comment by Donni1966** [comment] 2020-04-21 09:58
Puh :-)
try my best 

here some log details
Apr 21 11:56:20 Homebridge01 homebridge[20042]: 2020-04-21T09:56:20.851Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ec b6 3f 04 40 2b e5 2e c6 54 e4 4e 4e 4e 15 15 60>
Apr 21 11:56:20 Homebridge01 homebridge[20042]: 2020-04-21T09:56:20.851Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ec b6 3f 04 40 2b e5 2e c6 54 e4 4e 4e 4e 15 15 60>
Apr 21 11:56:20 Homebridge01 homebridge[20042]: 2020-04-21T09:56:20.852Z thing:miio:240158366 <- Message: `{"id":113,"result":[0]}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.003Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ec e0 4b 81 00 f2 01 1d 26 e3 9e 10 ca c1 16 4d c6>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.003Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ec e0 4b 81 00 f2 01 1d 26 e3 9e 10 ca c1 16 4d c6>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.004Z thing:miio:240158366 <- Message: `{"id":122,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getCurrentHumidifierState Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.071Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ec 4a fe 7b 55 99 07 8b a8 db f7 0a 4f 60 79 a5 a3>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.071Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ec 4a fe 7b 55 99 07 8b a8 db f7 0a 4f 60 79 a5 a3>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.071Z thing:miio:240158366 <- Message: `{"id":123,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getActive Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.106Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ec 68 76 c8 e9 f2 d6 43 5a 63 6b 52 b5 08 3c 1a bd>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.107Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ec 68 76 c8 e9 f2 d6 43 5a 63 6b 52 b5 08 3c 1a bd>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.108Z thing:miio:240158366 <- Message: `{"id":114,"result":[0]}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.221Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ec 02 60 07 1a 3a ab e5 02 fe 7d 82 6c b4 e6 dc 32>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.221Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ec 02 60 07 1a 3a ab e5 02 fe 7d 82 6c b4 e6 dc 32>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.222Z thing:miio:240158366 <- Message: `{"id":125,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getWaterLevel Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.317Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 3f cf 28 72 1f 51 48 ba 5c e9 0e 50 a8 f3 36 79>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.317Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 3f cf 28 72 1f 51 48 ba 5c e9 0e 50 a8 f3 36 79>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.318Z thing:miio:240158366 <- Message: `{"id":126,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getRotationSpeed Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.361Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 23 35 30 d9 70 dd 46 43 e8 b9 f9 36 28 81 fd a1>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.364Z thing:miio:240158366 <- Message: `{"id":127,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getSwitch1 Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.403Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ed d1 5b 4a e8 90 03 ee 25 72 65 5d 78 24 f9 0e 0d>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.404Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ed d1 5b 4a e8 90 03 ee 25 72 65 5d 78 24 f9 0e 0d>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.404Z thing:miio:240158366 <- Message: `{"id":115,"result":[70]}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.458Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed e3 df 5e ca c3 1d d1 70 88 b8 52 16 6b d0 5f 13>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.459Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed e3 df 5e ca c3 1d d1 70 88 b8 52 16 6b d0 5f 13>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.459Z thing:miio:240158366 <- Message: `{"id":129,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getCurrentRelativeHumidity Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.553Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 49 25 74 3c eb 58 9f 4b b6 a2 8b 75 93 29 6b 82>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.553Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 49 25 74 3c eb 58 9f 4b b6 a2 8b 75 93 29 6b 82>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.554Z thing:miio:240158366 <- Message: `{"id":229,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getWaterLevel Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.577Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ed 46 fd 30 46 cb ce 23 01 c8 ff aa 6e f4 f7 bc 0a>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.577Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ed 46 fd 30 46 cb ce 23 01 c8 ff aa 6e f4 f7 bc 0a>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.578Z thing:miio:240158366 <- Message: `{"id":116,"result":[1]}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.654Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 11 f7 5d 79 d1 a8 f8 aa da d5 78 d8 6d 69 49 7f>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.658Z thing:miio:240158366 <- Message: `{"id":429,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getCurrentHumidifierState Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.680Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 0f fc 5a 1c 50 49 8a 66 0a a3 c3 e9 74 75 49 99>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.680Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed 0f fc 5a 1c 50 49 8a 66 0a a3 c3 e9 74 75 49 99>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.701Z thing:miio:240158366 <- Message: `{"id":529,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getActive Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.715Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ed 0f 21 d1 bb 50 e1 58 ea 87 4c f7 44 cc 4f bb 1d>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.716Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 0e 50 86 9e 00 02 36 ed 0f 21 d1 bb 50 e1 58 ea 87 4c f7 44 cc 4f bb 1d>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.718Z thing:miio:240158366 <- Message: `{"id":117,"result":[4]}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.765Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed b5 18 94 aa 91 2d cb a5 18 87 5d f7 79 88 ac c4>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.768Z miio:packet <- <Buffer 21 31 00 60 00 00 00 00 0e 50 86 9e 00 02 36 ed b5 18 94 aa 91 2d cb a5 18 87 5d f7 79 88 ac c4>
Apr 21 11:56:21 Homebridge01 homebridge[20042]: 2020-04-21T09:56:21.769Z thing:miio:240158366 <- Message: `{"id":729,"error":{"code":-30012,"message":"busy."}}`
Apr 21 11:56:21 Homebridge01 homebridge[20042]: [4/21/2020, 11:56:21] [Luftbefeuchter Offie] getWaterLevel Error: busy.
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at Socket.emit (events.js:310:20)
Apr 21 11:56:21 Homebridge01 homebridge[20042]:     at UDP.onMessage [as onmessage] (dgram.js:924:8) {
Apr 21 11:56:21 Homebridge01 homebridge[20042]:   code: -30012
Apr 21 11:56:21 Homebridge01 homebridge[20042]: }

**Comment by Donni1966** [comment] 2020-04-21 09:59
the values are changing or temp. State etc. and the seems realistic

**Comment by PietroLubini** [comment] 2020-04-21 17:09
> Hi.
> 
> 1. very thanx to support the ne model.
> 
> i updated and i get humintity an Temp and an control, but in the log of the HB is see this
> 
> ```
> at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
> at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
> at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
> at Socket.emit (events.js:310:20)
> at UDP.onMessage [as onmessage] (dgram.js:924:8) {
> ```
> 
> code: -30012
> }
> [4/21/2020, 11:25:34] [Luftbefeuchter Offie] getWaterLevel Error: busy.
> at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
> at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
> at Socket. (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
> at Socket.emit (events.js:310:20)
> at UDP.onMessage [as onmessage] (dgram.js:924:8) {
> code: -30012
> }
> [4/21/2020, 11:25:34] [Luftbefeuchter Offie] getRotationSpeed Error: busy.
> at Object.reject (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:475:13)
> at DeviceInfo.onMessage (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:374:8)
> at Socket. (/usr/local/lib/node_modules/homebridge-mi-humidifier/node_modules/miio/lib/network.js:160:11)
> at Socket.emit (events.js:310:20)
> at UDP.onMessage [as onmessage] (dgram.js:924:8) {
> code: -30012
> }
> 
> any idear?

It happens when there is an error in getting data from Humidifier (e.g. WiFi connection error). Can't you control mode of Humidifier in HomeKit (Fan Speed).
WaterLevel is not very useful for mjjsq version because device returns 0 or 1 only (0 - empty, 1 - non empty).

**Comment by Donni1966** [comment] 2020-04-21 18:24
Yes i can control switch on and of an control but no correctly. 

there is a bottom on the front side. This botten knows Level 1 (so lowest) and level 5 highes. The switch switch of the device by pressing more than 3 seconds. The regulator in HomeKit only controll only to level 5, not to the other level. the switch in HomeKit switch off


. 

So i understand the blue controller in control the volume the fog in this 4 Level. but this not work. 

I you move the slider he every times comes up to level 5 and i you put the slider down, nothing happened. 

in the software you an set 4 Level Low Medium high and Humidity and than in the MI Software you can set the humidity to an special level. Thats in my understanding the sliders word in the HomeKit. 

Than the are to switch in the software. LED and Sound on off. The not supported by HomeKit Plugin. But is not importend.

i take some screen shots and a small video if is helpful.  

the device is near an good 2.4 ghz wifi. I can hav trouble with this wifi, because 2.4 GHZ Wifi a a lot of around me. I test this with an network analyzer. 

thanx or support this. 


![IMG_0040](https://user-images.githubusercontent.com/61660957/79899464-22b5c300-840d-11ea-8ef6-19b5a4ff6578.png)
![IMG_0041](https://user-images.githubusercontent.com/61660957/79899507-32350c00-840d-11ea-81b1-e3478c248e90.png)
![IMG_0042](https://user-images.githubusercontent.com/61660957/79899534-3a8d4700-840d-11ea-8cd4-bd7b605ef02b.png)

**Comment by PietroLubini** [comment] 2020-04-21 20:29
> Yes i can control switch on and of an control but no correctly.
> 
> there is a bottom on the front side. This botten knows Level 1 (so lowest) and level 5 highes. The switch switch of the device by pressing more than 3 seconds. The regulator in HomeKit only controll only to level 5, not to the other level. the switch in HomeKit switch off
> 
> .
> 
> So i understand the blue controller in control the volume the fog in this 4 Level. but this not work.
> 
> I you move the slider he every times comes up to level 5 and i you put the slider down, nothing happened.
> 
> in the software you an set 4 Level Low Medium high and Humidity and than in the MI Software you can set the humidity to an special level. Thats in my understanding the sliders word in the HomeKit.
> 
> Than the are to switch in the software. LED and Sound on off. The not supported by HomeKit Plugin. But is not importend.
> 
> i take some screen shots and a small video if is helpful.
> 
> the device is near an good 2.4 ghz wifi. I can hav trouble with this wifi, because 2.4 GHZ Wifi a a lot of around me. I test this with an network analyzer.
> 
> thanx or support this.

> ![IMG_0040](https://user-images.githubusercontent.com/61660957/79899464-22b5c300-840d-11ea-8ef6-19b5a4ff6578.png)
> ![IMG_0041](https://user-images.githubusercontent.com/61660957/79899507-32350c00-840d-11ea-81b1-e3478c248e90.png)
> ![IMG_0042](https://user-images.githubusercontent.com/61660957/79899534-3a8d4700-840d-11ea-8cd4-bd7b605ef02b.png)

1) Mode control:
Plugin supports 5 positions: 0 - off; 1 - low; 2 - medium; 3 - high; 4 - humidity (off). See pictures above
![Mode0 - off](https://user-images.githubusercontent.com/19411059/79910715-d3c95700-8427-11ea-8e58-d1584bbd6e66.jpeg)
![Mode1 - low](https://user-images.githubusercontent.com/19411059/79910717-d461ed80-8427-11ea-9432-a3eb016f49b3.jpeg)
![Mode2 - medium](https://user-images.githubusercontent.com/19411059/79910719-d461ed80-8427-11ea-86b7-bf6e73a540db.jpeg)
![Mode3 - high](https://user-images.githubusercontent.com/19411059/79910720-d4fa8400-8427-11ea-967d-24e4dd7fe60f.jpeg)
![Mode4 - humidity](https://user-images.githubusercontent.com/19411059/79910713-d2982a00-8427-11ea-81aa-3c65437b93b2.jpeg)

2) LED indicator is actually supported - it is Oscillate switch
3) Notification sounds is not supported - just didn't find any similar to Oscillate button characteristic.

**Comment by Donni1966** [comment] 2020-04-21 20:41
Hi, 

i see in the grouped View no slider :-) or the other switch. Now i ungroup it and the control make more sense - only water level not work. But you explain this. 
![Screenshot 2020-04-21 22 38 05](https://user-images.githubusercontent.com/61660957/79911667-0459c280-8421-11ea-9f40-b99976e0091b.png)
![Screenshot 2020-04-21 22 37 55](https://user-images.githubusercontent.com/61660957/79911676-07ed4980-8421-11ea-8bfa-b32a24067cb0.png)

this is the grouped view. 

and by the way. There is an problem on 2.4 ghz network. overlaps on channel and so on. 

thanx or help

**Closed** 2020-04-28 18:10 UTC
Labels: enhancement
