### ISSUE TITLE
2.0.0-beta.x

### ISSUE THREAD

**Issue by DJay-X** [russtone/homebridge-mi-humidifier#46] opened 2020-12-16 18:50 UTC
Thanks for the beta. I have the feeling using "platforms" is a good way.
However...

zhimi.humidifier.ca4

LED - not working
Buzzer - not working
Temperature - not working

```
[16.12.2020, 19:39:43] [MiHumidifier] Fail to set property 'led_brightness'. Error: Invalid result: {"did":"led_brightness","siid":5,"piid":1,"code":-4004}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)

[16.12.2020, 19:39:45] [MiHumidifier] Fail to set property 'led_brightness'. Error: Invalid result: {"did":"led_brightness","siid":5,"piid":1,"code":-4004}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)

[16.12.2020, 19:39:46] [MiHumidifier] Fail to set property 'led_brightness'. Error: Invalid result: {"did":"led_brightness","siid":5,"piid":1,"code":-4004}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)

[16.12.2020, 19:39:47] [MiHumidifier] Fail to set property 'led_brightness'. Error: Invalid result: {"did":"led_brightness","siid":5,"piid":1,"code":-4004}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at Brightness.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)
[16.12.2020, 19:45:14] [MiHumidifier] Fail to set property 'mode'. Error: Invalid result: {"did":"mode","siid":2,"piid":5,"code":-4002}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)

[16.12.2020, 19:45:17] [MiHumidifier] Fail to set property 'mode'. Error: Invalid result: {"did":"mode","siid":2,"piid":5,"code":-4002}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at RotationSpeed.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)

[16.12.2020, 19:46:15] [MiHumidifier] Fail to set property 'led_brightness'. Error: Invalid result: {"did":"led_brightness","siid":5,"piid":1,"code":-4004}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)

```

```
  {
            "platform": "MiHumidifier",
            "devices": [
                {
                    "name": "Luftbefeuchter",
                    "address": "xxx.xxx.xxx.xx",
                    "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "model": "zhimi.humidifier.ca4",
                    "updateInterval": 30,
                    "ledBulb": {
                        "enabled": true,
                        "name": "Luftbefeuchter LED"
                    },
                    "buzzerSwitch": {
                        "enabled": true,
                        "name": "Luftbefeuchter Buzzer"
                    },
                    "temperatureSensor": {
                        "enabled": true,
                        "name": "Luftbefeuchter Temperatur"
                    },
                    "humiditySensor": {
                        "enabled": true,
                        "name": "Luftbefeuchter Luftfeuchtigkeit"
                    }
                }
            ]
        },
```

![Napkin 16 12 20, 7 51 22 PM](https://user-images.githubusercontent.com/3874239/102393003-1b64aa80-3fd8-11eb-8cf8-704c47a04f0c.png)

**Comment by bubffm** [comment] 2020-12-16 19:04
I can confirm the "Brightness" Error message.  

As I had set buzzer and temperature to false, I did not notice those. But having now activated them, I can confirm those bugs reported by @djay as well.

**Comment by russtone** [comment] 2020-12-16 19:16
I've just published fix for 'led_brightness', 2.0.0-beta.2

**Comment by bubffm** [comment] 2020-12-16 19:26
Thanks, Brightness Error is fixed

**Comment by russtone** [comment] 2020-12-16 19:49
Could you please collect some debug logs by running homebridge like this:
`DEBUG=miio-api* homebridge`

**Comment by DJay-X** [comment] 2020-12-16 21:11
Thanks @russtone 

- Temp works now.

- LED seems to be reversed? Switch is off but display is on. And when using brightness switch turns on but at 2%  the switch the device display is off. 0% Display is full brightens but Switch off. There seems a mishmash.

- When using fan speed set to 0% there is an error.

```
[16.12.2020, 21:56:31] [MiHumidifier] Fail to set property 'mode'. Error: Invalid result: {"did":"mode","siid":2,"piid":5,"code":-4002}
    at Proto.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/protocols/protocol.js:43:19)
    at BaseHumidifier.setProp (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:134:13)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-mi-humidifier/dist/devices/humidifier.js:94:28)
```

**Comment by russtone** [comment] 2020-12-17 08:45
I've published a new beta which should resolve led inverse, fan speed and buzzer.

**Comment by bubffm** [comment] 2020-12-17 09:41
As far as I can tell, this fixes the issues.

Some cosmetics: 
- The buzzer has TWO switches. One for "Power", one for "Activate". As the buzzer is either on or off, I guess one of those two would suffice.
- Different Icons are being used to switch on the screen and the buzzer

On stability, I can already say this is a vast improvement over version 1.

Thanks very much

**Comment by bubffm** [comment] 2020-12-17 09:48
Do you still need logs? If so, I am not quite sure how/where to execute the "DEBUG=miio-api* homebridge" command.

**Comment by russtone** [comment] 2020-12-17 10:15
No, thanks, I think I've already found the most of the errors. As for issues you mentioned:

- I've removed "Active" property of the buzzer, so this I think this is related to homebridge or homekit cache.
- Buzzer uses Switch service and led uses Lightbulb service, because it also needs ability to change brightness. Thats why icons are different.
- This is limitation of homekit. "Rotation speed" has "percentage" unit type https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/gen/HomeKit.ts#L2015. And as I can see there is no other unit type such as step: https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/Characteristic.ts#L34

**Comment by lvtz** [comment] 2020-12-17 11:32
Hey, I've tried to update to new beta version, but after Homebridge server restart, I've got this error:

```
[12/17/2020, 12:30:39 PM] Loading 2 accessories...
[12/17/2020, 12:30:39 PM] Error loading accessory requested in your config.json at position 1
[12/17/2020, 12:30:40 PM] Error: The requested accessory 'MiHumidifier' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:345:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Migration to beta requires any additional changes in config?

**Comment by russtone** [comment] 2020-12-17 11:39
@lvtz, yes, example of new config can be found here: the example here https://www.npmjs.com/package/homebridge-mi-humidifier/v/2.0.0-beta.2

**Comment by lvtz** [comment] 2020-12-17 11:41
@russtone yes, thank you. I've just moved configuration to new config style, and it works!

**Comment by lvtz** [comment] 2020-12-17 11:52
Can you confirm setting `enabled` from `true` to `false` should hide it? I've trying to remove details about temperature, humidity, buzzer switch and led, because I don't need it, but these details still appears in my Home app and Homebridge dashboard.

```
          "ledBulb": {
            "enabled": true,
            "name": "Humidifier LED"
          },
          "buzzerSwitch": {
            "enabled": true,
            "name": "Humidifier Buzzer"
          },
          "temperatureSensor": {
            "enabled": true,
            "name": "Humidifier Temperature"
          },
          "humiditySensor": {
            "enabled": true,
            "name": "Humidifier Humidity"
          }
```

**Comment by bubffm** [comment] 2020-12-17 12:21
> Can you confirm setting `enabled` from `true` to `false` should hide it? I've trying to remove details about temperature, humidity, buzzer switch and led, because I don't need it, but these details still appears in my Home app and Homebridge dashboard.
> 

I think thats an issue of homebridge keeping those (removed) devices in its cache. you may have to clear the device cache.

**Comment by russtone** [comment] 2020-12-17 12:24
Problem with saving configuration from UI should be fixed in the latest version, thanks to @pisikaki (#48)

**Comment by bubffm** [comment] 2020-12-17 13:49
@russtone 

One suggestion on the handling of the "accessories". (LED, Buzzer, temperature, humidity):

I don't want to see those as separate assessors on my homebridge. However, when I set them to "false" they also disappear from the list of properties of the humidifier itself - where I would like to have them for the rare occasion where I want to switch on the LED or activate the buzzer etc.

Is there a way to differentiate between seeing them as a controllable item within the device versus seeing them as a separate accessory listing?

I could be thinking about something like this:

`"ledBulb": {
                        "enabled": true,
                         "visible": false,
                        "name": "Befeuchter Esszimmer LED"`

thanks for considering

**Comment by russtone** [comment] 2020-12-17 14:53
> @russtone
> 
> One suggestion on the handling of the "accessories". (LED, Buzzer, temperature, humidity):
> 
> I don't want to see those as separate assessors on my homebridge. However, when I set them to "false" they also disappear from the list of properties of the humidifier itself - where I would like to have them for the occasion when I want to switch on the LED or activate the buzzer etc.
> 
> Is there a way to differentiate between seeing them as a controllable item within the device versus seeing them as a separate accessory listing?
> 
> I could be thinking about something like this:
> 
> > 
> 
> "ledBulb": {
> "enabled": true,
> "**listed**": **false**,
> "name": "Befeuchter Esszimmer LED"
> },
> 
> thanks for considering

Unfortunately, I don't think it is possible due to homekit limitations. Currently, humidifier in homekit has some characteristics like power, current humidity, etc. (see all here https://developers.homebridge.io/#/service/HumidifierDehumidifier). If we add other characteristics to humidifier they won't be shown in Home.app. That's why to add ability to control led we need to add separate lightbulb service.
If someone knows how to implement this please send me some examples (maybe you've seen this in other plugins) and I will try to add this feature.

**Comment by lvtz** [comment] 2020-12-17 19:00
Can we get formatted error message than throwing all error details in log?

It doesn't look very good at this moment.

![img](https://user-images.githubusercontent.com/18595528/102531368-795dc480-40a2-11eb-951b-7283d6058f2b.png)

**Comment by pandizajner** [comment] 2020-12-17 23:18
I'm having a problem with displaying the temperature properly. It shows `2*C` while is supposed to show `22*C`.

**Comment by russtone** [comment] 2021-01-19 19:06
All problems from this issue seems to be fixed, so I am closing it.

**Closed by russtone** 2021-01-19 19:06 UTC
Labels: v2
